"""message

Revision ID: e4b3487e6c8a
Revises: 85555da16d21
Create Date: 2022-09-27 23:26:46.204976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4b3487e6c8a'
down_revision = '85555da16d21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Auctions', 'Name')
    op.add_column('Auctions', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Auctions', sa.Column('Name', sa.VARCHAR(), nullable=False))
    op.drop_column('Auctions', 'name')
    # ### end Alembic commands ###
