"""message

Revision ID: ee8db8624985
Revises: e4b3487e6c8a
Create Date: 2022-09-27 23:28:40.970768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee8db8624985'
down_revision = 'e4b3487e6c8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Auctions', sa.Column('location', sa.String(), nullable=True))
    op.add_column('Auctions', sa.Column('country', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Auctions', 'country')
    op.drop_column('Auctions', 'location')
    # ### end Alembic commands ###
