"""Add TokenSession

Revision ID: fa1c0a06e6c8
Revises: 1355e4c3b940
Create Date: 2022-09-01 14:28:45.722779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa1c0a06e6c8'
down_revision = '1355e4c3b940'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TokenSessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['userid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_TokenSessions_id'), 'TokenSessions', ['id'], unique=False)
    op.create_index(op.f('ix_TokenSessions_token'), 'TokenSessions', ['token'], unique=True)
    op.add_column('users', sa.Column('validated', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('role', sa.String(), nullable=False))
    op.drop_column('users', 'role_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role_id', sa.INTEGER(), nullable=False))
    op.drop_column('users', 'role')
    op.drop_column('users', 'validated')
    op.drop_index(op.f('ix_TokenSessions_token'), table_name='TokenSessions')
    op.drop_index(op.f('ix_TokenSessions_id'), table_name='TokenSessions')
    op.drop_table('TokenSessions')
    # ### end Alembic commands ###
